### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by RogeredBacon** [morkeltry/GETmilk#20]
Create a README with info about stuff.

**Comment by azayneeva** [comment]
Our project architecture
![img_20170809_123205481](https://user-images.githubusercontent.com/24795752/29128194-089cf2fa-7d1b-11e7-9e88-7c8b45765e64.jpg)

**Comment by andrewMacmurray** [comment]
You guys have a great readme 🎉  maybe close this?
